default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: /cloudsql/portafoliobackend:us-central1:gatos
  database: gatos
  username: postgres
  password: p31FelJ15gHdhymF

development: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: /cloudsql/portafoliobackend:us-central1:gatos
  database: gatos
  username: postgres
  password: p31FelJ15gHdhymF

  production: &default
   adapter: postgresql
   encoding: utf8
   pool: 5
   host: /cloudsql/portafoliobackend:us-central1:gatos
   database: gatos
   username: postgres
   password: p31FelJ15gHdhymF