default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  encoding: utf8
  pool: 5
  database: example
  username: postgres
  password: admin123

production:
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: /cloudsql/portafoliobackend:us-central1:gatos
  database: gatos
  username: postgres
  password: p31FelJ15gHdhymF

development: &default
  adapter: postgresql
  host: localhost
  port: 5432
  encoding: utf8
  pool: 5
  database: example
  username: postgres
  password: admin123